# configure some default settings
[default]

# configure the development environment settings
[development]
flask_debug = true
extensions = ["flask_debugtoolbar:DebugToolbarExtension"]
debug_tb_enabled = true
debug_tb_intercept_redirects = false

# configure the production environment settings
[production]
flask_debug = false

